public enum CategoryAnamnese {
    HISTOIRE_MALADIE,
    SUIVI_MEDICAL,
    STRUCTURE_FAMILIALE,
    DYNAMIQUE_FAMILIALE,
    ANTECEDENTS_FAMILIAUX,
    CONDITIONS_NATALES,
    DEVELOPPEMENT_PSYCHOMOTEUR,
    DEVELOPPEMENT_LANGAGIER,
    CARACTERE_COMPORTEMENT,
}
